# Generated by Django 5.1 on 2026-03-08 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_userclub_and_owner_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_books_id', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=30)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('to_read', 'To Read'), ('reading', 'Reading'), ('read', 'Read')], default='to_read', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('length_minutes', models.PositiveIntegerField()),
                ('meeting_type', models.CharField(choices=[('virtual', 'Virtual'), ('in_person', 'In person')], default='virtual', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['meeting_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userclub',
            options={'ordering': ['-joined_at']},
        ),
        migrations.RenameField(
            model_name='club',
            old_name='location',
            new_name='club_location',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='current_book_id',
            new_name='max_members',
        ),
        migrations.AlterUniqueTogether(
            name='userclub',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='club',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='club',
            name='meeting_type',
        ),
        migrations.AddField(
            model_name='club',
            name='club_meeting_mode',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('in_person', 'In person')], default='virtual', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userclub',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='userclub',
            constraint=models.UniqueConstraint(fields=('user', 'club'), name='unique_user_per_club'),
        ),
        migrations.AddConstraint(
            model_name='userclub',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('club',), name='unique_owner_per_club'),
        ),
        migrations.AddField(
            model_name='announcementthread',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='bookclub.club'),
        ),
        migrations.AddField(
            model_name='announcementthread',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubbook',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_books_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubbook',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_books', to='bookclub.club'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='bookclub.club'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='bookclub.meeting'),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='meetingattendance',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='unique_booking_per_meeting_user'),
        ),
    ]
