# Generated by Django 5.1 on 2026-03-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_announcementthread_clubbook_meeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbook',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='clubbook',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
