# Generated by Django 5.1 on 2026-03-10 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_clubbook_cover_image_clubbook_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userclub',
            name='unique_user_per_club',
        ),
        migrations.RemoveConstraint(
            model_name='userclub',
            name='unique_owner_per_club',
        ),
        migrations.RemoveField(
            model_name='userclub',
            name='club',
        ),
        migrations.RemoveField(
            model_name='userclub',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='meetingattendance',
            name='unique_booking_per_meeting_user',
        ),
        migrations.RemoveField(
            model_name='announcementthread',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clubbook',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='length_minutes',
        ),
        migrations.RemoveField(
            model_name='meetingattendance',
            name='user',
        ),
        migrations.AddField(
            model_name='announcementthread',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='bookclub.club'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_bookings', to='bookclub.member'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendance',
            constraint=models.UniqueConstraint(fields=('meeting', 'member'), name='unique_booking_per_meeting_member'),
        ),
        migrations.DeleteModel(
            name='UserClub',
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user', 'club'), name='unique_user_per_club'),
        ),
    ]
