# Generated by Django 5.1 on 2026-03-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0007_club_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clubbook',
            constraint=models.UniqueConstraint(fields=('club', 'google_books_id'), name='unique_google_book_per_club'),
        ),
    ]
