# Generated by Django 5.1 on 2026-03-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0008_club_unique_google_book_per_club'),
    ]

    operations = []
