# Generated by Django 5.1 on 2026-03-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0009_remove_club_unique_google_book_per_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbook',
            name='google_books_id',
            field=models.CharField(max_length=100),
        ),
    ]
